### ISSUE TITLE
No contact address (besides linkedIn)

### ISSUE THREAD

**Issue by raphaelbosshard** [zach-albia/zach-albia.github.io#1]
There's currently no contact information besides LinkedIn, which makes it hard to reach you.

**Comment by zalbia** [comment]
On the main page, besides LinkedIn, I have links on the sidebar to my Github, Twitter, and a mailto URI so I'm afraid I'm not quite following you here. What would you suggest?

**Comment by raphaelbosshard** [comment]
Haha, I'm stupid. Didn't explore the site enough. :D
